//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnipInsight.Forms.Features.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SnipInsight.Forms.Features.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AudioVideoSource_NoAudio {
            get {
                return ResourceManager.GetString("AudioVideoSource_NoAudio", resourceCulture);
            }
        }
        
        public static string Close_Content {
            get {
                return ResourceManager.GetString("Close_Content", resourceCulture);
            }
        }
        
        public static string Close_ToolTip {
            get {
                return ResourceManager.GetString("Close_ToolTip", resourceCulture);
            }
        }
        
        public static string Delete_Content {
            get {
                return ResourceManager.GetString("Delete_Content", resourceCulture);
            }
        }
        
        public static string Exception_Dialog_Text {
            get {
                return ResourceManager.GetString("Exception_Dialog_Text", resourceCulture);
            }
        }
        
        public static string Exception_Dialog_Title {
            get {
                return ResourceManager.GetString("Exception_Dialog_Title", resourceCulture);
            }
        }
        
        public static string Pause_Content {
            get {
                return ResourceManager.GetString("Pause_Content", resourceCulture);
            }
        }
        
        public static string Pause_ToolTip {
            get {
                return ResourceManager.GetString("Pause_ToolTip", resourceCulture);
            }
        }
        
        public static string PreviewStart_Content {
            get {
                return ResourceManager.GetString("PreviewStart_Content", resourceCulture);
            }
        }
        
        public static string PreviewStart_ToolTip {
            get {
                return ResourceManager.GetString("PreviewStart_ToolTip", resourceCulture);
            }
        }
        
        public static string PreviewStop_Content {
            get {
                return ResourceManager.GetString("PreviewStop_Content", resourceCulture);
            }
        }
        
        public static string RecordingStop_Text {
            get {
                return ResourceManager.GetString("RecordingStop_Text", resourceCulture);
            }
        }
        
        public static string RecordingStop_ToolTip {
            get {
                return ResourceManager.GetString("RecordingStop_ToolTip", resourceCulture);
            }
        }
        
        public static string Record_Content {
            get {
                return ResourceManager.GetString("Record_Content", resourceCulture);
            }
        }
        
        public static string Record_ToolTip {
            get {
                return ResourceManager.GetString("Record_ToolTip", resourceCulture);
            }
        }
        
        public static string Capture_Content {
            get {
                return ResourceManager.GetString("Capture_Content", resourceCulture);
            }
        }
        
        public static string Capture_ToolTip {
            get {
                return ResourceManager.GetString("Capture_ToolTip", resourceCulture);
            }
        }
        
        public static string AudioVideo_ErrorReport {
            get {
                return ResourceManager.GetString("AudioVideo_ErrorReport", resourceCulture);
            }
        }
        
        public static string AudioVideo_NoAudioReceived {
            get {
                return ResourceManager.GetString("AudioVideo_NoAudioReceived", resourceCulture);
            }
        }
        
        public static string AudioVideo_NoSamplesProcessed {
            get {
                return ResourceManager.GetString("AudioVideo_NoSamplesProcessed", resourceCulture);
            }
        }
        
        public static string AudioVideo_NoSuitableAudioStream {
            get {
                return ResourceManager.GetString("AudioVideo_NoSuitableAudioStream", resourceCulture);
            }
        }
        
        public static string AudioVideo_NoTranscodeAudioType {
            get {
                return ResourceManager.GetString("AudioVideo_NoTranscodeAudioType", resourceCulture);
            }
        }
        
        public static string AudioVideoSource_NoVideo {
            get {
                return ResourceManager.GetString("AudioVideoSource_NoVideo", resourceCulture);
            }
        }
        
        public static string CameraView_title {
            get {
                return ResourceManager.GetString("CameraView_title", resourceCulture);
            }
        }
        
        public static string Camera_Cancel {
            get {
                return ResourceManager.GetString("Camera_Cancel", resourceCulture);
            }
        }
        
        public static string Camera_Select {
            get {
                return ResourceManager.GetString("Camera_Select", resourceCulture);
            }
        }
        
        public static string Camera_SelectToolTip {
            get {
                return ResourceManager.GetString("Camera_SelectToolTip", resourceCulture);
            }
        }
        
        public static string Camera_TakePicture {
            get {
                return ResourceManager.GetString("Camera_TakePicture", resourceCulture);
            }
        }
        
        public static string Camera_TakeToolTip {
            get {
                return ResourceManager.GetString("Camera_TakeToolTip", resourceCulture);
            }
        }
        
        public static string Photo_Content {
            get {
                return ResourceManager.GetString("Photo_Content", resourceCulture);
            }
        }
        
        public static string Photo_ToolTip {
            get {
                return ResourceManager.GetString("Photo_ToolTip", resourceCulture);
            }
        }
        
        public static string Publish_Failed {
            get {
                return ResourceManager.GetString("Publish_Failed", resourceCulture);
            }
        }
        
        public static string Publish_Succeed {
            get {
                return ResourceManager.GetString("Publish_Succeed", resourceCulture);
            }
        }
        
        public static string Publish_WatchLink {
            get {
                return ResourceManager.GetString("Publish_WatchLink", resourceCulture);
            }
        }
        
        public static string Menu_Share {
            get {
                return ResourceManager.GetString("Menu_Share", resourceCulture);
            }
        }
        
        public static string Menu_Share_Email {
            get {
                return ResourceManager.GetString("Menu_Share_Email", resourceCulture);
            }
        }
        
        public static string Menu_Share_Embed {
            get {
                return ResourceManager.GetString("Menu_Share_Embed", resourceCulture);
            }
        }
        
        public static string Menu_Share_Link {
            get {
                return ResourceManager.GetString("Menu_Share_Link", resourceCulture);
            }
        }
        
        public static string FirstRun_Annotate_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Annotate_Heading", resourceCulture);
            }
        }
        
        public static string FirstRun_Grab_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Grab_Heading", resourceCulture);
            }
        }
        
        public static string FirstRun_Share_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Share_Heading", resourceCulture);
            }
        }
        
        public static string FirstRun_Intro_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Intro_Heading", resourceCulture);
            }
        }
        
        public static string WindowTitle_FirstRun {
            get {
                return ResourceManager.GetString("WindowTitle_FirstRun", resourceCulture);
            }
        }
        
        public static string WindowTitle_Main {
            get {
                return ResourceManager.GetString("WindowTitle_Main", resourceCulture);
            }
        }
        
        public static string WindowTitle_Toast {
            get {
                return ResourceManager.GetString("WindowTitle_Toast", resourceCulture);
            }
        }
        
        public static string WindowTitle_Tool {
            get {
                return ResourceManager.GetString("WindowTitle_Tool", resourceCulture);
            }
        }
        
        public static string FirstRun_Annotate_Message {
            get {
                return ResourceManager.GetString("FirstRun_Annotate_Message", resourceCulture);
            }
        }
        
        public static string FirstRun_Intro_Message {
            get {
                return ResourceManager.GetString("FirstRun_Intro_Message", resourceCulture);
            }
        }
        
        public static string FirstRun_Share_Message {
            get {
                return ResourceManager.GetString("FirstRun_Share_Message", resourceCulture);
            }
        }
        
        public static string FirstRun_Grab_Message {
            get {
                return ResourceManager.GetString("FirstRun_Grab_Message", resourceCulture);
            }
        }
        
        public static string WindowsChrome_Close {
            get {
                return ResourceManager.GetString("WindowsChrome_Close", resourceCulture);
            }
        }
        
        public static string WindowsChrome_Maximize {
            get {
                return ResourceManager.GetString("WindowsChrome_Maximize", resourceCulture);
            }
        }
        
        public static string WindowsChrome_Minimize {
            get {
                return ResourceManager.GetString("WindowsChrome_Minimize", resourceCulture);
            }
        }
        
        public static string WindowsChrome_Restore {
            get {
                return ResourceManager.GetString("WindowsChrome_Restore", resourceCulture);
            }
        }
        
        public static string Progress_Upload {
            get {
                return ResourceManager.GetString("Progress_Upload", resourceCulture);
            }
        }
        
        public static string Progress_Video {
            get {
                return ResourceManager.GetString("Progress_Video", resourceCulture);
            }
        }
        
        public static string Link_Privacy {
            get {
                return ResourceManager.GetString("Link_Privacy", resourceCulture);
            }
        }
        
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        public static string Message_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Message_CopiedToClipboard", resourceCulture);
            }
        }
        
        public static string Message_LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("Message_LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        public static string Link_Terms {
            get {
                return ResourceManager.GetString("Link_Terms", resourceCulture);
            }
        }
        
        public static string Message_CopyToClipboardFailed {
            get {
                return ResourceManager.GetString("Message_CopyToClipboardFailed", resourceCulture);
            }
        }
        
        public static string KeyComboPicker_NotSupportCombination {
            get {
                return ResourceManager.GetString("KeyComboPicker_NotSupportCombination", resourceCulture);
            }
        }
        
        public static string KeyComboPicker_Updated {
            get {
                return ResourceManager.GetString("KeyComboPicker_Updated", resourceCulture);
            }
        }
        
        public static string Settings_AboutThisApp_Heading {
            get {
                return ResourceManager.GetString("Settings_AboutThisApp_Heading", resourceCulture);
            }
        }
        
        public static string Settings_Capture_Heading {
            get {
                return ResourceManager.GetString("Settings_Capture_Heading", resourceCulture);
            }
        }
        
        public static string Settings_Copyright_Text {
            get {
                return ResourceManager.GetString("Settings_Copyright_Text", resourceCulture);
            }
        }
        
        public static string Settings_Hotkeys_Heading {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Heading", resourceCulture);
            }
        }
        
        public static string Settings_PrivacyStatement_Button {
            get {
                return ResourceManager.GetString("Settings_PrivacyStatement_Button", resourceCulture);
            }
        }
        
        public static string Settings_General_Heading {
            get {
                return ResourceManager.GetString("Settings_General_Heading", resourceCulture);
            }
        }
        
        public static string Settings_Developers_Heading {
            get {
                return ResourceManager.GetString("Settings_Developers_Heading", resourceCulture);
            }
        }
        
        public static string Settings_Snipping_Heading {
            get {
                return ResourceManager.GetString("Settings_Snipping_Heading", resourceCulture);
            }
        }
        
        public static string Settings_Cognitive_Services_Heading {
            get {
                return ResourceManager.GetString("Settings_Cognitive_Services_Heading", resourceCulture);
            }
        }
        
        public static string Settings_ServiceAgreement_Button {
            get {
                return ResourceManager.GetString("Settings_ServiceAgreement_Button", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_NewCapture {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewCapture", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_NewPhoto {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewPhoto", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_NewWhiteboard {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewWhiteboard", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_Library {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Library", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Settings", resourceCulture);
            }
        }
        
        public static string TrayIcon_ContextMenuItem_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Exit", resourceCulture);
            }
        }
        
        public static string TrayIcon_ToolTip {
            get {
                return ResourceManager.GetString("TrayIcon_ToolTip", resourceCulture);
            }
        }
        
        public static string TrayIcon_BalloonTip_AppIsStillRunning_Text {
            get {
                return ResourceManager.GetString("TrayIcon_BalloonTip_AppIsStillRunning_Text", resourceCulture);
            }
        }
        
        public static string TrayIcon_BalloonTip_AppIsStillRunning_Title {
            get {
                return ResourceManager.GetString("TrayIcon_BalloonTip_AppIsStillRunning_Title", resourceCulture);
            }
        }
        
        public static string Settings_ShowToolbarOnDesktop {
            get {
                return ResourceManager.GetString("Settings_ShowToolbarOnDesktop", resourceCulture);
            }
        }
        
        public static string Settings_Delay {
            get {
                return ResourceManager.GetString("Settings_Delay", resourceCulture);
            }
        }
        
        public static string Settings_Delay_FormatString {
            get {
                return ResourceManager.GetString("Settings_Delay_FormatString", resourceCulture);
            }
        }
        
        public static string Menu_Share_OneNote {
            get {
                return ResourceManager.GetString("Menu_Share_OneNote", resourceCulture);
            }
        }
        
        public static string SendToOneNoteDialogDescription {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogDescription", resourceCulture);
            }
        }
        
        public static string SendToOneNoteDialogSendToButton {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogSendToButton", resourceCulture);
            }
        }
        
        public static string SendToOneNoteDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogTitle", resourceCulture);
            }
        }
        
        public static string SendToOneNoteProcessElevationMismatchDiaglogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteProcessElevationMismatchDiaglogMessage", resourceCulture);
            }
        }
        
        public static string SendToOneNoteProcessElevationMismatchDiaglogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteProcessElevationMismatchDiaglogTitle", resourceCulture);
            }
        }
        
        public static string Message_SendToOneNote_Failed {
            get {
                return ResourceManager.GetString("Message_SendToOneNote_Failed", resourceCulture);
            }
        }
        
        public static string Message_SendToOneNote_Succeeded {
            get {
                return ResourceManager.GetString("Message_SendToOneNote_Succeeded", resourceCulture);
            }
        }
        
        public static string SendToOneNoteFirstRunNotCompleteDialogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteFirstRunNotCompleteDialogMessage", resourceCulture);
            }
        }
        
        public static string SendToOneNoteFirstRunNotCompleteDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteFirstRunNotCompleteDialogTitle", resourceCulture);
            }
        }
        
        public static string SendToOneNoteRestartSnipDialogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteRestartSnipDialogMessage", resourceCulture);
            }
        }
        
        public static string SendToOneNoteRestartSnipDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteRestartSnipDialogTitle", resourceCulture);
            }
        }
        
        public static string Settings_ContentModerationStrength_FormatString {
            get {
                return ResourceManager.GetString("Settings_ContentModerationStrength_FormatString", resourceCulture);
            }
        }
        
        public static string ShareModerateWarning {
            get {
                return ResourceManager.GetString("ShareModerateWarning", resourceCulture);
            }
        }
        
        public static string Settings_EnableAI {
            get {
                return ResourceManager.GetString("Settings_EnableAI", resourceCulture);
            }
        }
        
        public static string Commit_Changes {
            get {
                return ResourceManager.GetString("Commit_Changes", resourceCulture);
            }
        }
        
        public static string LUIS_App_id {
            get {
                return ResourceManager.GetString("LUIS_App_id", resourceCulture);
            }
        }
        
        public static string API_Key_Not_Found {
            get {
                return ResourceManager.GetString("API_Key_Not_Found", resourceCulture);
            }
        }
        
        public static string Auto_open_editor {
            get {
                return ResourceManager.GetString("Auto_open_editor", resourceCulture);
            }
        }
        
        public static string Celebrity_Information {
            get {
                return ResourceManager.GetString("Celebrity_Information", resourceCulture);
            }
        }
        
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        public static string Confirm_Delete_List {
            get {
                return ResourceManager.GetString("Confirm_Delete_List", resourceCulture);
            }
        }
        
        public static string ContentModerator {
            get {
                return ResourceManager.GetString("ContentModerator", resourceCulture);
            }
        }
        
        public static string Copy_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_to_clipboard", resourceCulture);
            }
        }
        
        public static string Create_New_Event {
            get {
                return ResourceManager.GetString("Create_New_Event", resourceCulture);
            }
        }
        
        public static string Delete_Failed {
            get {
                return ResourceManager.GetString("Delete_Failed", resourceCulture);
            }
        }
        
        public static string Delete_Failed_List {
            get {
                return ResourceManager.GetString("Delete_Failed_List", resourceCulture);
            }
        }
        
        public static string Entity_Search {
            get {
                return ResourceManager.GetString("Entity_Search", resourceCulture);
            }
        }
        
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        public static string Erase_All {
            get {
                return ResourceManager.GetString("Erase_All", resourceCulture);
            }
        }
        
        public static string Exception_at_celebrities {
            get {
                return ResourceManager.GetString("Exception_at_celebrities", resourceCulture);
            }
        }
        
        public static string Exception_at_landmark {
            get {
                return ResourceManager.GetString("Exception_at_landmark", resourceCulture);
            }
        }
        
        public static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        public static string Image_Analysis {
            get {
                return ResourceManager.GetString("Image_Analysis", resourceCulture);
            }
        }
        
        public static string Image_Not_Loaded {
            get {
                return ResourceManager.GetString("Image_Not_Loaded", resourceCulture);
            }
        }
        
        public static string Image_Search {
            get {
                return ResourceManager.GetString("Image_Search", resourceCulture);
            }
        }
        
        public static string Image_to_Text {
            get {
                return ResourceManager.GetString("Image_to_Text", resourceCulture);
            }
        }
        
        public static string OCR_Text {
            get {
                return ResourceManager.GetString("OCR_Text", resourceCulture);
            }
        }
        
        public static string Insight_Not_Found {
            get {
                return ResourceManager.GetString("Insight_Not_Found", resourceCulture);
            }
        }
        
        public static string Key_Restart {
            get {
                return ResourceManager.GetString("Key_Restart", resourceCulture);
            }
        }
        
        public static string Landmark_Information {
            get {
                return ResourceManager.GetString("Landmark_Information", resourceCulture);
            }
        }
        
        public static string LUIS_App {
            get {
                return ResourceManager.GetString("LUIS_App", resourceCulture);
            }
        }
        
        public static string LUIS_Key {
            get {
                return ResourceManager.GetString("LUIS_Key", resourceCulture);
            }
        }
        
        public static string More_information {
            get {
                return ResourceManager.GetString("More_information", resourceCulture);
            }
        }
        
        public static string My_Snips {
            get {
                return ResourceManager.GetString("My_Snips", resourceCulture);
            }
        }
        
        public static string No_Browser {
            get {
                return ResourceManager.GetString("No_Browser", resourceCulture);
            }
        }
        
        public static string Pen_Toggle {
            get {
                return ResourceManager.GetString("Pen_Toggle", resourceCulture);
            }
        }
        
        public static string Please_try_again {
            get {
                return ResourceManager.GetString("Please_try_again", resourceCulture);
            }
        }
        
        public static string Popular_landmark {
            get {
                return ResourceManager.GetString("Popular_landmark", resourceCulture);
            }
        }
        
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        public static string Send_Email {
            get {
                return ResourceManager.GetString("Send_Email", resourceCulture);
            }
        }
        
        public static string Sharing_Snip {
            get {
                return ResourceManager.GetString("Sharing_Snip", resourceCulture);
            }
        }
        
        public static string Sharing_Snip_Name {
            get {
                return ResourceManager.GetString("Sharing_Snip_Name", resourceCulture);
            }
        }
        
        public static string Similar_Images {
            get {
                return ResourceManager.GetString("Similar_Images", resourceCulture);
            }
        }
        
        public static string Similar_Images_Web {
            get {
                return ResourceManager.GetString("Similar_Images_Web", resourceCulture);
            }
        }
        
        public static string Similar_Products {
            get {
                return ResourceManager.GetString("Similar_Products", resourceCulture);
            }
        }
        
        public static string Suggested_Insights {
            get {
                return ResourceManager.GetString("Suggested_Insights", resourceCulture);
            }
        }
        
        public static string Text_Recognition {
            get {
                return ResourceManager.GetString("Text_Recognition", resourceCulture);
            }
        }
        
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        public static string UpdateKeys {
            get {
                return ResourceManager.GetString("UpdateKeys", resourceCulture);
            }
        }
        
        public static string Who_is_this {
            get {
                return ResourceManager.GetString("Who_is_this", resourceCulture);
            }
        }
        
        public static string ContentModerator_Endpoint {
            get {
                return ResourceManager.GetString("ContentModerator_Endpoint", resourceCulture);
            }
        }
        
        public static string LUIS_Endpoint {
            get {
                return ResourceManager.GetString("LUIS_Endpoint", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Last_7_days {
            get {
                return ResourceManager.GetString("Last_7_days", resourceCulture);
            }
        }
        
        public static string Choose_an_area {
            get {
                return ResourceManager.GetString("Choose_an_area", resourceCulture);
            }
        }
        
        public static string Config_CopyClipboard {
            get {
                return ResourceManager.GetString("Config_CopyClipboard", resourceCulture);
            }
        }
        
        public static string Config_EnableAI {
            get {
                return ResourceManager.GetString("Config_EnableAI", resourceCulture);
            }
        }
        
        public static string Config_OpenEditor {
            get {
                return ResourceManager.GetString("Config_OpenEditor", resourceCulture);
            }
        }
        
        public static string TopMenuWindow_Snip {
            get {
                return ResourceManager.GetString("TopMenuWindow_Snip", resourceCulture);
            }
        }
        
        public static string Celebrity_News {
            get {
                return ResourceManager.GetString("Celebrity_News", resourceCulture);
            }
        }
        
        public static string NewsAboutFormat {
            get {
                return ResourceManager.GetString("NewsAboutFormat", resourceCulture);
            }
        }
        
        public static string Image_of_Text {
            get {
                return ResourceManager.GetString("Image_of_Text", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        public static string Translate_to {
            get {
                return ResourceManager.GetString("Translate_to", resourceCulture);
            }
        }
        
        public static string Settings_Service_Endpoints_Title {
            get {
                return ResourceManager.GetString("Settings_Service_Endpoints_Title", resourceCulture);
            }
        }
        
        public static string Settings_Service_Keys_Title {
            get {
                return ResourceManager.GetString("Settings_Service_Keys_Title", resourceCulture);
            }
        }
        
        public static string Settings_Browse {
            get {
                return ResourceManager.GetString("Settings_Browse", resourceCulture);
            }
        }
        
        public static string Settings_Current_Location {
            get {
                return ResourceManager.GetString("Settings_Current_Location", resourceCulture);
            }
        }
        
        public static string Settings_Save_Share_Options {
            get {
                return ResourceManager.GetString("Settings_Save_Share_Options", resourceCulture);
            }
        }
        
        public static string Settings_Set_Default_Foloder {
            get {
                return ResourceManager.GetString("Settings_Set_Default_Foloder", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string Insights_Begin_Snip {
            get {
                return ResourceManager.GetString("Insights_Begin_Snip", resourceCulture);
            }
        }
        
        public static string Insights_Looking {
            get {
                return ResourceManager.GetString("Insights_Looking", resourceCulture);
            }
        }
        
        public static string Insights_No_Infor_Available {
            get {
                return ResourceManager.GetString("Insights_No_Infor_Available", resourceCulture);
            }
        }
        
        public static string Insights_Turn_On_Message {
            get {
                return ResourceManager.GetString("Insights_Turn_On_Message", resourceCulture);
            }
        }
        
        public static string Landmark_Information_Button_Text {
            get {
                return ResourceManager.GetString("Landmark_Information_Button_Text", resourceCulture);
            }
        }
        
        public static string Color_Picker_Colors {
            get {
                return ResourceManager.GetString("Color_Picker_Colors", resourceCulture);
            }
        }
        
        public static string Color_Picker_Weight {
            get {
                return ResourceManager.GetString("Color_Picker_Weight", resourceCulture);
            }
        }
        
        public static string Insights_Save_Default_File_Name {
            get {
                return ResourceManager.GetString("Insights_Save_Default_File_Name", resourceCulture);
            }
        }
        
        public static string Insights_Cancel_Save {
            get {
                return ResourceManager.GetString("Insights_Cancel_Save", resourceCulture);
            }
        }
        
        public static string Insights_Save {
            get {
                return ResourceManager.GetString("Insights_Save", resourceCulture);
            }
        }
        
        public static string Insights_Save_File {
            get {
                return ResourceManager.GetString("Insights_Save_File", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        public static string Open_Library_Folder {
            get {
                return ResourceManager.GetString("Open_Library_Folder", resourceCulture);
            }
        }
    }
}
