//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnipInsight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnipInsight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  API Key not configured in setting.
        /// </summary>
        public static string API_Key_Not_Found {
            get {
                return ResourceManager.GetString("API_Key_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with your microphone. Please try restarting your device..
        /// </summary>
        public static string AudioVideo_ErrorReport {
            get {
                return ResourceManager.GetString("AudioVideo_ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The microphone is not recording. Please check your device, and try again..
        /// </summary>
        public static string AudioVideo_NoAudioReceived {
            get {
                return ResourceManager.GetString("AudioVideo_NoAudioReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was recorded. Please try a longer recording..
        /// </summary>
        public static string AudioVideo_NoSamplesProcessed {
            get {
                return ResourceManager.GetString("AudioVideo_NoSamplesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The microphone is not supported. Please try a different audio device..
        /// </summary>
        public static string AudioVideo_NoSuitableAudioStream {
            get {
                return ResourceManager.GetString("AudioVideo_NoSuitableAudioStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to record using the microphone. Please try a different audio device..
        /// </summary>
        public static string AudioVideo_NoTranscodeAudioType {
            get {
                return ResourceManager.GetString("AudioVideo_NoTranscodeAudioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No microphone.
        /// </summary>
        public static string AudioVideoSource_NoAudio {
            get {
                return ResourceManager.GetString("AudioVideoSource_NoAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera.
        /// </summary>
        public static string AudioVideoSource_NoVideo {
            get {
                return ResourceManager.GetString("AudioVideoSource_NoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically open editor on snip.
        /// </summary>
        public static string Auto_open_editor {
            get {
                return ResourceManager.GetString("Auto_open_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Camera_Cancel {
            get {
                return ResourceManager.GetString("Camera_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Camera_Select {
            get {
                return ResourceManager.GetString("Camera_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a camera.
        /// </summary>
        public static string Camera_SelectToolTip {
            get {
                return ResourceManager.GetString("Camera_SelectToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        public static string Camera_TakePicture {
            get {
                return ResourceManager.GetString("Camera_TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        public static string Camera_TakeToolTip {
            get {
                return ResourceManager.GetString("Camera_TakeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip camera.
        /// </summary>
        public static string CameraView_title {
            get {
                return ResourceManager.GetString("CameraView_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture_Content {
            get {
                return ResourceManager.GetString("Capture_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture  your screen.
        /// </summary>
        public static string Capture_ToolTip {
            get {
                return ResourceManager.GetString("Capture_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrity Information.
        /// </summary>
        public static string Celebrity_Information {
            get {
                return ResourceManager.GetString("Celebrity_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close_Content {
            get {
                return ResourceManager.GetString("Close_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Snip Insights application.
        /// </summary>
        public static string Close_ToolTip {
            get {
                return ResourceManager.GetString("Close_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        public static string Commit_Changes {
            get {
                return ResourceManager.GetString("Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this snip?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} snips?.
        /// </summary>
        public static string Confirm_Delete_List {
            get {
                return ResourceManager.GetString("Confirm_Delete_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Moderator.
        /// </summary>
        public static string ContentModerator {
            get {
                return ResourceManager.GetString("ContentModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Moderator Endpoint.
        /// </summary>
        public static string ContentModerator_Endpoint {
            get {
                return ResourceManager.GetString("ContentModerator_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string Copied_To_Clipboard {
            get {
                return ResourceManager.GetString("Copied_To_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard after a snip.
        /// </summary>
        public static string Copy_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        public static string Create_New_Event {
            get {
                return ResourceManager.GetString("Create_New_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Content {
            get {
                return ResourceManager.GetString("Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion failed..
        /// </summary>
        public static string Delete_Failed {
            get {
                return ResourceManager.GetString("Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion failed for {0} item(s).
        /// </summary>
        public static string Delete_Failed_List {
            get {
                return ResourceManager.GetString("Delete_Failed_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Search.
        /// </summary>
        public static string Entity_Search {
            get {
                return ResourceManager.GetString("Entity_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Search Endpoint.
        /// </summary>
        public static string Entity_Search_Endpoint {
            get {
                return ResourceManager.GetString("Entity_Search_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase All.
        /// </summary>
        public static string Erase_All {
            get {
                return ResourceManager.GetString("Erase_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser.
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception at celebrities: .
        /// </summary>
        public static string Exception_at_celebrities {
            get {
                return ResourceManager.GetString("Exception_at_celebrities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception at landmark: .
        /// </summary>
        public static string Exception_at_landmark {
            get {
                return ResourceManager.GetString("Exception_at_landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! It looks like something has gone wrong. A software problem has occurred in Snip Insights . Not to worry, we&apos;ve reported it to the team. You may continue to use the application, but some features may not work as expected..
        /// </summary>
        public static string Exception_Dialog_Text {
            get {
                return ResourceManager.GetString("Exception_Dialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights error.
        /// </summary>
        public static string Exception_Dialog_Title {
            get {
                return ResourceManager.GetString("Exception_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        public static string FirstRun_Annotate_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Annotate_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on insights to see similar images, auto-naming and more..
        /// </summary>
        public static string FirstRun_Annotate_Message {
            get {
                return ResourceManager.GetString("FirstRun_Annotate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights.
        /// </summary>
        public static string FirstRun_Grab_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Grab_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag to capture any window or area of your screen..
        /// </summary>
        public static string FirstRun_Grab_Message {
            get {
                return ResourceManager.GetString("FirstRun_Grab_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights AI.
        /// </summary>
        public static string FirstRun_Intro_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Intro_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the tool window or assign shorcuts to access features..
        /// </summary>
        public static string FirstRun_Intro_Message {
            get {
                return ResourceManager.GetString("FirstRun_Intro_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show-and-tell.
        /// </summary>
        public static string FirstRun_Share_Heading {
            get {
                return ResourceManager.GetString("FirstRun_Share_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit, share and save your snips, all in the same window..
        /// </summary>
        public static string FirstRun_Share_Message {
            get {
                return ResourceManager.GetString("FirstRun_Share_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter.
        /// </summary>
        public static string Highlighter {
            get {
                return ResourceManager.GetString("Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Analysis.
        /// </summary>
        public static string Image_Analysis {
            get {
                return ResourceManager.GetString("Image_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Analysis (Computer Vision) Endpoint.
        /// </summary>
        public static string Image_Analysis_Endpoint {
            get {
                return ResourceManager.GetString("Image_Analysis_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, image cannot be loaded.
        /// </summary>
        public static string Image_Not_Loaded {
            get {
                return ResourceManager.GetString("Image_Not_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Search.
        /// </summary>
        public static string Image_Search {
            get {
                return ResourceManager.GetString("Image_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Search (Bing Search) Endpoint.
        /// </summary>
        public static string Image_Search_Endpoint {
            get {
                return ResourceManager.GetString("Image_Search_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image to Text.
        /// </summary>
        public static string Image_to_Text {
            get {
                return ResourceManager.GetString("Image_to_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] InkCursor {
            get {
                object obj = ResourceManager.GetObject("InkCursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find insights!.
        /// </summary>
        public static string Insight_Not_Found {
            get {
                return ResourceManager.GetString("Insight_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys have been updated.
        ///Please restart the application to apply changes. .
        /// </summary>
        public static string Key_Restart {
            get {
                return ResourceManager.GetString("Key_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a supported combination.
        /// </summary>
        public static string KeyComboPicker_NotSupportCombination {
            get {
                return ResourceManager.GetString("KeyComboPicker_NotSupportCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string KeyComboPicker_Updated {
            get {
                return ResourceManager.GetString("KeyComboPicker_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark Information.
        /// </summary>
        public static string Landmark_Information {
            get {
                return ResourceManager.GetString("Landmark_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://go.microsoft.com/fwlink/?LinkId=521839.
        /// </summary>
        public static string Link_Privacy {
            get {
                return ResourceManager.GetString("Link_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.microsoft.com/en-us/servicesagreement/.
        /// </summary>
        public static string Link_Terms {
            get {
                return ResourceManager.GetString("Link_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUIS App ID.
        /// </summary>
        public static string LUIS_App {
            get {
                return ResourceManager.GetString("LUIS_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2891e896-28de-4a0e-818e-504de767d08f.
        /// </summary>
        public static string LUIS_App_id {
            get {
                return ResourceManager.GetString("LUIS_App_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUIS Endpoint.
        /// </summary>
        public static string LUIS_Endpoint {
            get {
                return ResourceManager.GetString("LUIS_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUIS Key.
        /// </summary>
        public static string LUIS_Key {
            get {
                return ResourceManager.GetString("LUIS_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Menu_Share {
            get {
                return ResourceManager.GetString("Menu_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Menu_Share_Email {
            get {
                return ResourceManager.GetString("Menu_Share_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed.
        /// </summary>
        public static string Menu_Share_Embed {
            get {
                return ResourceManager.GetString("Menu_Share_Embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Menu_Share_Link {
            get {
                return ResourceManager.GetString("Menu_Share_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote.
        /// </summary>
        public static string Menu_Share_OneNote {
            get {
                return ResourceManager.GetString("Menu_Share_OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string Message_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Message_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy to clipboard! Please try again later..
        /// </summary>
        public static string Message_CopyToClipboardFailed {
            get {
                return ResourceManager.GetString("Message_CopyToClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        public static string Message_LinkCopiedToClipboard {
            get {
                return ResourceManager.GetString("Message_LinkCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to OneNote failed.
        /// </summary>
        public static string Message_SendToOneNote_Failed {
            get {
                return ResourceManager.GetString("Message_SendToOneNote_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip sent to OneNote.
        /// </summary>
        public static string Message_SendToOneNote_Succeeded {
            get {
                return ResourceManager.GetString("Message_SendToOneNote_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string More_information {
            get {
                return ResourceManager.GetString("More_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Snips.
        /// </summary>
        public static string My_Snips {
            get {
                return ResourceManager.GetString("My_Snips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet browser found. Please install a browser and try again.
        /// </summary>
        public static string No_Browser {
            get {
                return ResourceManager.GetString("No_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Popup.
        /// </summary>
        public static string Notification_popup {
            get {
                return ResourceManager.GetString("Notification_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Notification_shortcut_dismiss {
            get {
                return ResourceManager.GetString("Notification_shortcut_dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string Notification_shortcut_editor {
            get {
                return ResourceManager.GetString("Notification_shortcut_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string Notification_shortcut_folder {
            get {
                return ResourceManager.GetString("Notification_shortcut_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Editor.
        /// </summary>
        public static string Open_editor {
            get {
                return ResourceManager.GetString("Open_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string Open_folder {
            get {
                return ResourceManager.GetString("Open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause_Content {
            get {
                return ResourceManager.GetString("Pause_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause your recording.
        /// </summary>
        public static string Pause_ToolTip {
            get {
                return ResourceManager.GetString("Pause_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Toggle.
        /// </summary>
        public static string Pen_Toggle {
            get {
                return ResourceManager.GetString("Pen_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo_Content {
            get {
                return ResourceManager.GetString("Photo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        public static string Photo_ToolTip {
            get {
                return ResourceManager.GetString("Photo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string Please_try_again {
            get {
                return ResourceManager.GetString("Please_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular landmark.
        /// </summary>
        public static string Popular_landmark {
            get {
                return ResourceManager.GetString("Popular_landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PreviewStart_Content {
            get {
                return ResourceManager.GetString("PreviewStart_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch a preview of your recording.
        /// </summary>
        public static string PreviewStart_ToolTip {
            get {
                return ResourceManager.GetString("PreviewStart_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string PreviewStop_Content {
            get {
                return ResourceManager.GetString("PreviewStop_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading your snip so it&apos;ll be easy to share....
        /// </summary>
        public static string Progress_Upload {
            get {
                return ResourceManager.GetString("Progress_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing video....
        /// </summary>
        public static string Progress_Video {
            get {
                return ResourceManager.GetString("Progress_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish failed!.
        /// </summary>
        public static string Publish_Failed {
            get {
                return ResourceManager.GetString("Publish_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish succeed!.
        /// </summary>
        public static string Publish_Succeed {
            get {
                return ResourceManager.GetString("Publish_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to View.
        /// </summary>
        public static string Publish_WatchLink {
            get {
                return ResourceManager.GetString("Publish_WatchLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record_Content {
            get {
                return ResourceManager.GetString("Record_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record audio and write on your picture.
        /// </summary>
        public static string Record_ToolTip {
            get {
                return ResourceManager.GetString("Record_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string RecordingStop_Text {
            get {
                return ResourceManager.GetString("RecordingStop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string RecordingStop_ToolTip {
            get {
                return ResourceManager.GetString("RecordingStop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different scales on monitors have been detected. This can introduce issues on the snips you take. Please set the same scale on every monitor..
        /// </summary>
        public static string Screen_Diferent_Scale_Factor_Detected {
            get {
                return ResourceManager.GetString("Screen_Diferent_Scale_Factor_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Saved!.
        /// </summary>
        public static string Screenshot_saved {
            get {
                return ResourceManager.GetString("Screenshot_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string Send_Email {
            get {
                return ResourceManager.GetString("Send_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a section or page to insert the Snip:.
        /// </summary>
        public static string SendToOneNoteDialogDescription {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to selected location.
        /// </summary>
        public static string SendToOneNoteDialogSendToButton {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogSendToButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Snip to OneNote.
        /// </summary>
        public static string SendToOneNoteDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote has not been configured. Launch and configure OneNote first and then try again..
        /// </summary>
        public static string SendToOneNoteFirstRunNotCompleteDialogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteFirstRunNotCompleteDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote not configured.
        /// </summary>
        public static string SendToOneNoteFirstRunNotCompleteDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteFirstRunNotCompleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights is unable to open OneNote because {0} is running as Administrator and {1} is not. Close OneNote and try again..
        /// </summary>
        public static string SendToOneNoteProcessElevationMismatchDiaglogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteProcessElevationMismatchDiaglogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open OneNote.
        /// </summary>
        public static string SendToOneNoteProcessElevationMismatchDiaglogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteProcessElevationMismatchDiaglogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights needs to be restarted. Click OK to restart Snip Insights..
        /// </summary>
        public static string SendToOneNoteRestartSnipDialogMessage {
            get {
                return ResourceManager.GetString("SendToOneNoteRestartSnipDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Snip Insights.
        /// </summary>
        public static string SendToOneNoteRestartSnipDialogTitle {
            get {
                return ResourceManager.GetString("SendToOneNoteRestartSnipDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string Settings_AboutThisApp_Heading {
            get {
                return ResourceManager.GetString("Settings_AboutThisApp_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture preferences.
        /// </summary>
        public static string Settings_Capture_Heading {
            get {
                return ResourceManager.GetString("Settings_Capture_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services.
        /// </summary>
        public static string Settings_Cognitive_Services_Heading {
            get {
                return ResourceManager.GetString("Settings_Cognitive_Services_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share image moderator strength: {0} %.
        /// </summary>
        public static string Settings_ContentModerationStrength_FormatString {
            get {
                return ResourceManager.GetString("Settings_ContentModerationStrength_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 Microsoft Corporation.
        /// </summary>
        public static string Settings_Copyright_Text {
            get {
                return ResourceManager.GetString("Settings_Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay screen capture: {0} second(s).
        /// </summary>
        public static string Settings_Delay_FormatString {
            get {
                return ResourceManager.GetString("Settings_Delay_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay screen capture.
        /// </summary>
        public static string Settings_DelayScreenCapture {
            get {
                return ResourceManager.GetString("Settings_DelayScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AI assistance.
        /// </summary>
        public static string Settings_EnableAI {
            get {
                return ResourceManager.GetString("Settings_EnableAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For developers.
        /// </summary>
        public static string Settings_ForDevelopers {
            get {
                return ResourceManager.GetString("Settings_ForDevelopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General_Heading {
            get {
                return ResourceManager.GetString("Settings_General_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys - (Ctrl + Alt + AnyKey).
        /// </summary>
        public static string Settings_Hotkeys_Heading {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Hotkeys (Ctrl + Alt + Any supported key).
        /// </summary>
        public static string Settings_Hotkeys_Heading1 {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * MacOS Hotkeys (Cmd + Option + Any Supported key).
        /// </summary>
        public static string Settings_Hotkeys_Heading2 {
            get {
                return ResourceManager.GetString("Settings_Hotkeys_Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string Settings_PrivacyStatement_Button {
            get {
                return ResourceManager.GetString("Settings_PrivacyStatement_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK CAPTURE.
        /// </summary>
        public static string Settings_QUICK {
            get {
                return ResourceManager.GetString("Settings_QUICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        public static string Settings_QUIT {
            get {
                return ResourceManager.GetString("Settings_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Snip Insights when Windows starts.
        /// </summary>
        public static string Settings_RunWhenWindowsStarts_Label {
            get {
                return ResourceManager.GetString("Settings_RunWhenWindowsStarts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Services Agreement.
        /// </summary>
        public static string Settings_ServiceAgreement_Button {
            get {
                return ResourceManager.GetString("Settings_ServiceAgreement_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toolbar on the desktop.
        /// </summary>
        public static string Settings_ShowToolbarOnDesktop {
            get {
                return ResourceManager.GetString("Settings_ShowToolbarOnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNIP.
        /// </summary>
        public static string Settings_SNIP {
            get {
                return ResourceManager.GetString("Settings_SNIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipping.
        /// </summary>
        public static string Settings_Snipping_Heading {
            get {
                return ResourceManager.GetString("Settings_Snipping_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image may contain inappropriate content, would you like to proceed anyway?.
        /// </summary>
        public static string ShareModerateWarning {
            get {
                return ResourceManager.GetString("ShareModerateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing a snip with you.
        /// </summary>
        public static string Sharing_Snip {
            get {
                return ResourceManager.GetString("Sharing_Snip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing a snip of &apos;{0}&apos; with you.
        /// </summary>
        public static string Sharing_Snip_Name {
            get {
                return ResourceManager.GetString("Sharing_Snip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the notification toast after a snip.
        /// </summary>
        public static string Show_toast {
            get {
                return ResourceManager.GetString("Show_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrity.
        /// </summary>
        public static string Side_Celebrity_Information {
            get {
                return ResourceManager.GetString("Side_Celebrity_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Side_Information {
            get {
                return ResourceManager.GetString("Side_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark.
        /// </summary>
        public static string Side_Landmark_Information {
            get {
                return ResourceManager.GetString("Side_Landmark_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Side_Ocr {
            get {
                return ResourceManager.GetString("Side_Ocr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Images.
        /// </summary>
        public static string Side_Similar_Images {
            get {
                return ResourceManager.GetString("Side_Similar_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Side_Similar_Products {
            get {
                return ResourceManager.GetString("Side_Similar_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Images.
        /// </summary>
        public static string Similar_Images {
            get {
                return ResourceManager.GetString("Similar_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the web.
        /// </summary>
        public static string Similar_Images_Web {
            get {
                return ResourceManager.GetString("Similar_Images_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Products.
        /// </summary>
        public static string Similar_Products {
            get {
                return ResourceManager.GetString("Similar_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Insights.
        /// </summary>
        public static string Suggested_Insights {
            get {
                return ResourceManager.GetString("Suggested_Insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Recognition.
        /// </summary>
        public static string Text_Recognition {
            get {
                return ResourceManager.GetString("Text_Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Recognition (Computer Vision) Endpoint.
        /// </summary>
        public static string Text_Recognition_Endpoint {
            get {
                return ResourceManager.GetString("Text_Recognition_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator Text API Endpoint.
        /// </summary>
        public static string Translator_Endpoint {
            get {
                return ResourceManager.GetString("Translator_Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights is still running in the system tray, listening for hotkey commands to create new snips. Click here to stop showing this message..
        /// </summary>
        public static string TrayIcon_BalloonTip_AppIsStillRunning_Text {
            get {
                return ResourceManager.GetString("TrayIcon_BalloonTip_AppIsStillRunning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights is still running.
        /// </summary>
        public static string TrayIcon_BalloonTip_AppIsStillRunning_Title {
            get {
                return ResourceManager.GetString("TrayIcon_BalloonTip_AppIsStillRunning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_Library {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Capture.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_NewCapture {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Photo.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_NewPhoto {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Whiteboard.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_NewWhiteboard {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_NewWhiteboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TrayIcon_ContextMenuItem_Settings {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights.
        /// </summary>
        public static string TrayIcon_ToolTip {
            get {
                return ResourceManager.GetString("TrayIcon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateKeys.
        /// </summary>
        public static string UpdateKeys {
            get {
                return ResourceManager.GetString("UpdateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is this?.
        /// </summary>
        public static string Who_is_this {
            get {
                return ResourceManager.GetString("Who_is_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string WindowsChrome_Close {
            get {
                return ResourceManager.GetString("WindowsChrome_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string WindowsChrome_Maximize {
            get {
                return ResourceManager.GetString("WindowsChrome_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string WindowsChrome_Minimize {
            get {
                return ResourceManager.GetString("WindowsChrome_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Down.
        /// </summary>
        public static string WindowsChrome_Restore {
            get {
                return ResourceManager.GetString("WindowsChrome_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string WindowTitle_FirstRun {
            get {
                return ResourceManager.GetString("WindowTitle_FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights Editor.
        /// </summary>
        public static string WindowTitle_Main {
            get {
                return ResourceManager.GetString("WindowTitle_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string WindowTitle_Toast {
            get {
                return ResourceManager.GetString("WindowTitle_Toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip Insights Toolbar.
        /// </summary>
        public static string WindowTitle_Tool {
            get {
                return ResourceManager.GetString("WindowTitle_Tool", resourceCulture);
            }
        }
    }
}
